$(document).ready(function(){ //this makes sure the whole document is loaded before performing any actions
	
//colors
	$("#colors").click(function(){ //if colors is clicked, go to the first question
		$("#animals").hide();
		$("#success").hide();
		$("#question1").show();
	});
	//first
	$("#orange1").click(function(){ //if a wrong answer is clicked, show the wrong panel and eliminate that answer
		$("#orange1").hide();
		$("#wrong").show();
	});
	$("#red1").click(function(){ //if the correct answer is clicked, show the correct panel and move on to the next question
		$("#question1").hide();
		$("#wrong").hide();
		$("#correct").show();
		$("#question2").show();
	});
	$("#yellow1").click(function(){
		$("#yellow1").hide();
		$("#wrong").show();
	});
	$("#blue1").click(function(){
		$("#blue1").hide();
		$("#wrong").show();
	});
	//second
	$("#yellow2").click(function(){
		$("#yellow2").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#green2").click(function(){
		$("#green2").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#white2").click(function(){
		$("#white2").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#black2").click(function(){
		$("#question2").hide();
		$("#wrong").hide();
		$("#correct").show();
		$("#question3").show();
	});
	//third
	$("#yellow3").click(function(){
		$("#question3").hide();
		$("#correct").show();
		$("#wrong").hide();
		$("#question4").show();
	});
	$("#white3").click(function(){
		$("#white3").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#blue3").click(function(){
		$("#blue3").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#red3").click(function(){
		$("#red3").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	//fourth
	$("#orange4").click(function(){
		$("#orange4").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#blue4").click(function(){
		$("#question4").hide();
		$("#correct").show();
		$("#wrong").hide();
		$("#question5").show();
	});
	$("#green4").click(function(){
		$("#green4").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#black4").click(function(){
		$("#black4").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	//fifth
	$("#orange5").click(function(){
		$("#question5").hide();
		$("#correct").show();
		$("#wrong").hide();
		$("#question6").show();
	});
	$("#green5").click(function(){
		$("#green5").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#red5").click(function(){
		$("#red5").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#white5").click(function(){
		$("#white5").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	//sixth
	$("#blue6").click(function(){
		$("#blue6").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#black6").click(function(){
		$("#black6").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#yellow6").click(function(){
		$("#yellow6").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#green6").click(function(){
		$("#question6").hide();
		$("#correct").show();
		$("#wrong").hide();
		$("#question7").show();
	});
	//seventh
	$("#red7").click(function(){
		$("#red7").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#white7").click(function(){ //when you complete the exercise, show the success panel
		$("#question7").hide();
		$("#wrong").hide();
		$("#correct").hide();
		$("#success").show();
	});
	$("#blue7").click(function(){
		$("#blue7").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#orange7").click(function(){
		$("#orange7").hide();
		$("#correct").hide();
		$("#wrong").show();
	});



//animals
	$("#animals").click(function(){ //if animals is clicked, do the same functions as in colors
		$("#colors").hide();
		$("#success").hide();
		$("#question8").show();
	});
	//first
	$("#bird1").click(function(){
		$("#bird1").hide();
		$("#wrong").show();
	});
	$("#dog1").click(function(){
		$("#question8").hide();
		$("#wrong").hide();
		$("#correct").show();
		$("#question9").show();
	});
	$("#dolphin1").click(function(){
		$("#dolphin1").hide();
		$("#wrong").show();
	});
	$("#cow1").click(function(){
		$("#cow1").hide();
		$("#wrong").show();
	});
	//second
	$("#dolphin2").click(function(){
		$("#dolphin2").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#fish2").click(function(){
		$("#fish2").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#horse2").click(function(){
		$("#horse2").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#cat2").click(function(){
		$("#question9").hide();
		$("#wrong").hide();
		$("#correct").show();
		$("#question10").show();
	});
	//third
	$("#dolphin3").click(function(){
		$("#question10").hide();
		$("#correct").show();
		$("#wrong").hide();
		$("#question11").show();
	});
	$("#cat3").click(function(){
		$("#cat3").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#cow3").click(function(){
		$("#cow3").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#bird3").click(function(){
		$("#bird3").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	//fourth
	$("#dog4").click(function(){
		$("#dog4").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#horse4").click(function(){
		$("#question11").hide();
		$("#correct").show();
		$("#wrong").hide();
		$("#question12").show();
	});
	$("#cow4").click(function(){
		$("#cow4").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#fish4").click(function(){
		$("#fish4").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	//fifth
	$("#fish5").click(function(){
		$("#question12").hide();
		$("#correct").show();
		$("#wrong").hide();
		$("#question13").show();
	});
	$("#dog5").click(function(){
		$("#dog5").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#bird5").click(function(){
		$("#bird5").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#cat5").click(function(){
		$("#cat5").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	//sixth
	$("#horse6").click(function(){
		$("#horse6").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#dolphin6").click(function(){
		$("#dolphin6").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#fish6").click(function(){
		$("#fish6").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#cow6").click(function(){
		$("#question13").hide();
		$("#correct").show();
		$("#wrong").hide();
		$("#question14").show();
	});
	//seventh
	$("#cat7").click(function(){
		$("#cat7").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#bird7").click(function(){
		$("#question14").hide();
		$("#wrong").hide();
		$("#correct").hide();
		$("#success").show();
	});
	$("#cow7").click(function(){
		$("#cow7").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	$("#dog7").click(function(){
		$("#dog7").hide();
		$("#correct").hide();
		$("#wrong").show();
	});
	
});
